stages:
  - build
  - deploy

build:
  image: node:18
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  image: node:20
  stage: deploy
  script: 
    - npm install -g @azure/static-web-apps-cli
    - swa deploy dist/ --deployment-token $DEPLOYMENT_TOKEN
